server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:33060/shop_coupon
    username: root
    password: 12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    user: root
    password: 12345
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  application:
    name: SHOP-COUPON-MS