server:
  port: 8080
spring:
  datasource:
    url: mysql://root:BdEHb22gDF-aCcFeecG6BefddEGd--3B@viaduct.proxy.rlwy.net:59204/railway
    username: root
    password: BdEHb22gDF-aCcFeecG6BefddEGd--3B
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    user: root
    password: BdEHb22gDF-aCcFeecG6BefddEGd--3B
    enabled: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  application:
    name: SHOP-COUPON-MS